sonar.projectKey=AddressBook
sonar.working.directory=/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/.sonarqube/out/.sonar
sonar.projectBaseDir=/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook
sonar.pullrequest.cache.basepath=/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook

EACE259A-C091-4971-8C6B-615E0AFD5B9D.sonar.projectKey=AddressBook:EACE259A-C091-4971-8C6B-615E0AFD5B9D
EACE259A-C091-4971-8C6B-615E0AFD5B9D.sonar.projectName=AddressBook
EACE259A-C091-4971-8C6B-615E0AFD5B9D.sonar.projectBaseDir=/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook
EACE259A-C091-4971-8C6B-615E0AFD5B9D.sonar.sourceEncoding=utf-8
EACE259A-C091-4971-8C6B-615E0AFD5B9D.sonar.tests=
EACE259A-C091-4971-8C6B-615E0AFD5B9D.sonar.sources=\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/Addressbook.cs",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/AddressBookMain.cs",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/AddressBookMenu.cs",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/AddressBookUtilityImpl.cs",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/Contact.cs",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/IAddressBook.cs",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/Program.cs",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/UniversalLinkedList.cs",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/obj/Debug/net10.0/apphost",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/obj/AddressBook.csproj.nuget.dgspec.json",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/obj/project.assets.json",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/obj/Debug/net10.0/AddressBook.sourcelink.json",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/bin/Debug/net10.0/AddressBook.deps.json",\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/bin/Debug/net10.0/AddressBook.runtimeconfig.json"

EACE259A-C091-4971-8C6B-615E0AFD5B9D.sonar.cs.analyzer.projectOutPaths=\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/.sonarqube/out/0"
EACE259A-C091-4971-8C6B-615E0AFD5B9D.sonar.cs.roslyn.reportFilePaths=\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/.sonarqube/out/0/Issues.json"
EACE259A-C091-4971-8C6B-615E0AFD5B9D.sonar.cs.scanner.telemetry=\
"/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/.sonarqube/out/0/Telemetry.json"

EACE259A-C091-4971-8C6B-615E0AFD5B9D.sonar.working.directory=/Users/phoenix/Desktop/BridgeLabz-Training/collections-csharp-practice/scenario-based/AddressBook/.sonarqube/out/.sonar/mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=EACE259A-C091-4971-8C6B-615E0AFD5B9D

